### ISSUE TITLE
[Feature] Integrate Cargo tasks as commands

### ISSUE THREAD

**Issue by saviorisdead** [saviorisdead/RustyCode#10]
Integrate cargo subcommands as vscode-commands.

**Comment by KalitaAlexey** [comment]
I don't know is it allowed. Could I pass extra arguments to commands? That this arguments will be passed to cargo

**Comment by saviorisdead** [comment]
I think we have 2 ways here. First one, simplest, is to integrate basic command such as `build`, `run`, `test` as it is. Maybe with variants, like `build --release` and such. Second way, or more like addition to first is to add entry to settings, like `"customBuild": "cargo build --some-extra-arguments"`.

**Comment by KalitaAlexey** [comment]
I think that for each command should be configuration entry. This is good, I think.
