### ISSUE TITLE
Add an option to disable racer crash report

### ISSUE THREAD

**Issue by BusyJay** [saviorisdead/RustyCode#100]
Racer crash report is quite annoying, we may need an option to disable this report and restart it automatically after some interval.

**Comment by KalitaAlexey** [comment]
We can use https://code.visualstudio.com/Docs/extensionAPI/vscode-api#StatusBarItem to set
**Racer: {Status}**, where Status = On | Off | Error.
@saviorisdead any thoughts?

**Comment by saviorisdead** [comment]
Yeah, I think it's a good option.

**Comment by KalitaAlexey** [comment]
I will implement it.
