### ISSUE TITLE
Snippets from other editors

### ISSUE THREAD

**Issue by RustSnippets** [saviorisdead/RustyCode#102]
https://github.com/zargony/atom-language-rust/blob/master/snippets/rust.cson
https://github.com/abaez/ta-rust/blob/master/snippets.lua
https://github.com/freebroccolo/rust-snippets/blob/master/rust-snippets.el
https://github.com/darookee/vim-snippets/blob/master/UltiSnips/rust.snippets
https://github.com/rust-lang/sublime-rust/tree/master/snippets

Maybe you can derive some ideas from other editors and implement it in your project.

**Comment by CryZe** [comment]
I ported Sublime Rust's Snippets:
https://glot.io/snippets/eeejrplb7t

Some of them are commented out because for some reason they were already available? Not sure if RustyCode already added them or VSCode itself.

**Comment by saviorisdead** [comment]
Awesome, thanks, I'll take a look at this. Thank you!

**Comment by CryZe** [comment]
I added a lot more Snippets. All std macros and a lot of useful attributes:
https://glot.io/snippets/eefy6k24r2

**Comment by CryZe** [comment]
I did a Pull Request on the VS Code Repo itself and they are not sure if they should accept them or actually even delete the ones that they already have so that RustyCode can just do all of them. So maybe you should join the discussion @saviorisdead https://github.com/Microsoft/vscode/pull/6430#issuecomment-221087049

**Comment by saviorisdead** [comment]
I think you should move that PR here, so we can discuss it. I'm personally for it, but other people may have different opinions on that matter.

**Comment by CryZe** [comment]
I'm not sure how to add it to the plugin though, as I'm unfamiliar with plugin development for VS Code. Doing the PR for VS Code itself was easy as I just needed to locate the existing Snippets.

**Comment by saviorisdead** [comment]
I think this links can help you get started:
1) Official docs - [https://code.visualstudio.com/Docs/customization/userdefinedsnippets](https://code.visualstudio.com/Docs/customization/userdefinedsnippets)
2) And example from Go extension - [https://github.com/Microsoft/vscode-go/tree/master/snippets](https://github.com/Microsoft/vscode-go/tree/master/snippets)
[https://github.com/Microsoft/vscode-go/blob/master/package.json#L72](https://github.com/Microsoft/vscode-go/blob/master/package.json#L72)

**Comment by CryZe** [comment]
Thanks, I'll create a PR here then :)

**Comment by trixnz** [comment]
@CryZe saw that you hadn't done this yet and it was slowly driving me insane (having come from Atom) so I stole your PR :stuck_out_tongue:
