### ISSUE TITLE
Racer crashes very frequently

### ISSUE THREAD

**Issue by brashaw** [saviorisdead/RustyCode#106]
Just started using RustyCode a few days ago and have only messed around with some small files.  The Racer integration is really useful but it crashes ***so*** often and then doesn't start back up.

I'm not expecting stability to be great.  But is there a way I can manually start racer back up after it crashes?  A quick `Restart Racer` hotkey would be perfect.

**Comment by KalitaAlexey** [comment]
When #103 will be merged racer is going to be restarted after 1 second.

**Comment by seanjensengrey** [comment]
@brashaw I find it crashes less you don't use the mouse for navigation into

* Comments/Documentation
* Strings

**Comment by brashaw** [comment]
@KalitaAlexey Nice.  Hopefully it's reliable.

**Comment by KalitaAlexey** [comment]
@brashaw I already using it

**Comment by saviorisdead** [comment]
It merged, so you should try it.

**Comment by brashaw** [comment]
Works really good.  And no more errors every time it crashes, nice!
