### ISSUE TITLE
[Feature] Build on save

### ISSUE THREAD

**Issue by saviorisdead** [saviorisdead/RustyCode#11]
Add support for 'Build on save'.

**Comment by KalitaAlexey** [comment]
After we have check on save and keyboard shortcut for build I think this is obsolete.

**Comment by Draivin** [comment]
@KalitaAlexey unrelated, but previously you had a patch where it would automatically build examples if the open file was an example file, that made the `Build Example` commands obsolte, do you have any plans to submit that patch again?

**Comment by KalitaAlexey** [comment]
@Draivin No, because it is not good to build on save. Because it can be very slow. When you want to build or run you can press shortcut.
