### ISSUE TITLE
Null is not a valid value according to the configuration for many parameters

### ISSUE THREAD

**Issue by fulmicoton** [saviorisdead/RustyCode#114]
... Even though it is actually the default.

In recent version of Vs Code it triggers a warning in the status bar.
The issue is basically the same as what is reported [here (https://github.com/Microsoft/vscode/issues/2856).

**Comment by Draivin** [comment]
Hmm, why did you close the pull request?

**Comment by fulmicoton** [comment]
The PR is invalid. ["string", null] should be ["string", "null"] in all of the lines.

**Comment by saviorisdead** [comment]
Well, you can update your PR then :)

**Comment by fulmicoton** [comment]
sure
