### ISSUE TITLE
Unexpected undefined directory

### ISSUE THREAD

**Issue by BusyJay** [saviorisdead/RustyCode#118]
Hi, after upgrade rustycode to 0.14.2, it always create a directory called `undefined` in my project root, and use it as if it was `$HOME/.cargo`. I guess there must be something going wrong here since the directory name is `undefined`. And I really want rustycode to just use `$HOME/.cargo`.

**Comment by saviorisdead** [comment]
I see. Can you set `cargoHomePath` explicitly in settings for now and see if something changes?

**Comment by Draivin** [comment]
@saviorisdead I think if you change [this line] (https://github.com/saviorisdead/RustyCode/blob/2204727bac65a966ebf38455f8fcea693b8da77e/src/services/pathService.ts#L26) to
```typescript
return cargoHomePath || process.env['CARGO_HOME'] || '';
```
it will probably fix it.

Also, I believe it would be better to change [this line](https://github.com/saviorisdead/RustyCode/blob/2204727bac65a966ebf38455f8fcea693b8da77e/src/services/suggestService.ts#L110) to
```typescript
const racerEnv = Object.assign({}, process.env, {'CARGO_HOME': cargoHomePath});
```
So the current environment is not overwritten.

**Comment by BusyJay** [comment]
@saviorisdead, Yes, set `cargoHomePath` fixed it.

**Comment by saviorisdead** [comment]
I've updated path resolution for `CARGO_HOME` as @Draivin suggested, so also you could try leaving `cargoHomePath` null and see if it helped.

**Comment by BusyJay** [comment]
Just upgrade to 0.14.3, it works just fine without setting cargoHomePath.

**Comment by saviorisdead** [comment]
Awesome. So it fixed, thanks to you guys, @BusyJay, @Draivin. I'm closing this.
