### ISSUE TITLE
Check even though formatting failed

### ISSUE THREAD

**Issue by CryZe** [saviorisdead/RustyCode#121]
If you enable format on save, it'll try to format your code every time you save. But if formatting fails, it doesn't check your code for syntax errors anymore, which is bad, cause then you don't know where your mistakes are (if they aren't super trivial). So this should be fixed in my opinion.

Also on a side note: Having it pop up every time it can't format your code is fairly annoying, cause you have to click it away every single time (I'm not even sure if you can use the keyboard for that, I don't think there is a way).

**Comment by saviorisdead** [comment]
This seems to be fixed, so closing this :)
