### ISSUE TITLE
docker image with RustyCode

### ISSUE THREAD

**Issue by ctaggart** [saviorisdead/RustyCode#122]
I created a rust-vscode docker image with this extension preinstalled. I think it is a really easy way to try out Rust and RustyCode. Happy to receive feedback or suggestions. I put together a 10 minute video and will work on the blog post about it this week.

https://twitter.com/cmr0n/status/729508355144716288
https://github.com/ctaggart/rusty-vscode

**Comment by saviorisdead** [comment]
I really like the idea, to give easy option to try out RustyCode :) Good job!
