### ISSUE TITLE
Double brace on format

### ISSUE THREAD

**Issue by Minoost** [saviorisdead/RustyCode#124]
![animation](https://cloud.githubusercontent.com/assets/1381835/15206925/924f4f1c-185d-11e6-8b38-f669cabe0906.gif)

Notes:
- I feel this issue is somewhat similar to https://github.com/saviorisdead/RustyCode/issues/91
- Using ```rustfmt main.rs``` on command prompt works without a problem
- OS: ```Windows 10```
- VS Code: ```1.1.0```
- RustyCode: ```0.14.3```

**Comment by Frederick888** [comment]
Same here with RustyCode `0.14.4`
![snapshot8](https://cloud.githubusercontent.com/assets/4507647/15293939/8be1998c-1bcd-11e6-94ba-b0417f2a1b74.png)

Things get even worse if you try to format:

    fn main() {
        println!("Hello, world!");}

it will become

    fn main() {
        println!("Hello, world!");
    }    println!("Hello, world!");}

**Comment by henriiik** [comment]
if you update cscode to 1.1.1 this should be ficed. :)

original bug: https://github.com/Microsoft/vscode/issues/6281

**Comment by Frederick888** [comment]
Yeah, it's okay now. Thanks for your quick reply.

**Comment by Minoost** [comment]
It works now! :D
