### ISSUE TITLE
Format code is not looking at $PATH for `rustfmt`

### ISSUE THREAD

**Issue by nlordell** [saviorisdead/RustyCode#128]
```
$ which rustfmt
/Users/nlordell/.cargo/bin/rustfmt
```

Yet I still get the 'The "rustfmt" command is not available. Make sure it is installed.' message. Also noteworthy that executing something like the following in developer tools console works as expected:

```js
require("child_process").execFile("rustfmt", ["--version"], (_, stdout) => console.log(stdout))
// Output: 0.5.0
```

Mac OS X 10.11.4
VSCode 1.1.1
RustyCode 0.14.5

**Comment by nlordell** [comment]
Looks like the "env" being passed to child process needs to have PATH set as well (line 95 src/services/formatService.ts)

**Comment by saviorisdead** [comment]
I've merged the PR, so you can check if it fixed for you.

**Comment by nlordell** [comment]
fixed
