### ISSUE TITLE
Support for RUST_NEW_ERROR_FORMAT=true

### ISSUE THREAD

**Issue by zummenix** [saviorisdead/RustyCode#130]

**Comment by wycats** [comment]
Any progress on this?

**Comment by Draivin** [comment]
Related: https://github.com/saviorisdead/RustyCode/issues/146

Ideally, we would use the json build output, but as rustc only outputs one or the other, if we adopt the json build we won't be able to show the cargo build internally as if it was a console.

What are your thoughts on this?
