### ISSUE TITLE
Support "Cargo: Check" on projects with multiple targets

### ISSUE THREAD

**Issue by vhbit** [saviorisdead/RustyCode#131]
Right now if the project has multiple targets there is an error:

```
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
```

It would be great to have a way to configure a "default" target for checking through workspace configuration.

**Comment by isg** [comment]
This would be great. The one that would be most helpful for me is `--lib`, but specifying a default would be even better.

Would it be possible to have an option to `cargo check` all of the targets (e.g. run once as --lib, again for each --bin) by concatenating the outputs of each run?

**Comment by isg** [comment]
FWIW, setting to `clippy` seems to automatically use `--lib` in this case.
