### ISSUE TITLE
Suppress auto-closing of ' when typing lifetime signature

### ISSUE THREAD

**Issue by doxxx** [saviorisdead/RustyCode#133]
When I'm typing a lifetime signature, for example:

```
struct Stuff<'a> {
  blah: &'a str,
}
```

As I type the `'` in the struct declaration (both places), a closing `'` is automatically inserted, which I have to delete. It would be nice if this behaviour could be suppressed.

**Comment by zummenix** [comment]
Related vscode issue: https://github.com/Microsoft/vscode/issues/6295
and PR: https://github.com/Microsoft/vscode/pull/6377

**Comment by zummenix** [comment]
Starting from vscode 1.2.0 "Suppress auto-closing of ' for rust" works. I think the issue can be closed.

**Comment by doxxx** [comment]
Thanks, this is working nicely with the new version.
