### ISSUE TITLE
rust.checkWith setting is ignored

### ISSUE THREAD

**Issue by doxxx** [saviorisdead/RustyCode#134]
No matter what value I set for the `rust.checkWith` setting in my user settings.json, executing the `Cargo: Check` command always runs `rustc`.

**Comment by W4RH4WK** [comment]
Does this still happen? If so can you please post version information about your setup.

**Comment by doxxx** [comment]
Setting `rust.checkWith` to `build` uses `cargo build` as expected with the check triggered by save when `rust.checkOnSave` is `true`. However, explicitly invoking the `Cargo: Check` command always uses `cargo rustc -- -Zno-trans` regardless of what value `rust.checkWith` is set to.

Code 1.6.1, Rust Code 0.19.1.
Project: https://github.com/doxxx/grep-access

**Comment by W4RH4WK** [comment]
This is intended. The commands prefixed with `Cargo: ` always give you what they say. The setting `checkWith` is only relevant for checking a file automatically on save.

**Comment by doxxx** [comment]
I understand. Thanks!
