### ISSUE TITLE
Wrong comment leader for .toml

### ISSUE THREAD

**Issue by sorear** [saviorisdead/RustyCode#140]
If I use Control-/ in a toml file, vscode inserts a `//` leader, which is a syntax error; I think it should be `#`.

**Comment by saviorisdead** [comment]
Hey, `toml` support is managed by different extension (https://marketplace.visualstudio.com/items?itemName=be5invis.toml), but I can't find it's repository URL to open up a issue. I'll consider adding support to `RustyCode`.
Closing this as this is not related to `RustyCode`.
