### ISSUE TITLE
Make installation easier for the required binaries.

### ISSUE THREAD

**Issue by hannni** [saviorisdead/RustyCode#141]
Currently to get RustyCode fully up and running you additionally need to:

1. Install rust.
2. `cargo install racer` and `cargo install rustfmt`.
3. Add `.cargo/bin` (or corresponding on your machine) to `PATH`.
4. Download the rust source to some location and set `"rust.rustLangSrcPath"`.

I think each step could be streamlined a bit, right now it's easy to get one step wrong.

1. Because there are so many ways to install rust, it's maybe best to point to the rust website when no rust (including cargo) installation is found.
2. When racer or rustfmt aren't found, Rusty Code should offer installing them via `cargo install`.
3. Rusty Code should also look in the cargo binary directory for racer and rustfmt.
4. When `"rust.rustLangSrcPath"` isn't set yet, Rusty Code should offer selecting a directory and if the rust source isn't there yet download it.

**Comment by KalitaAlexey** [comment]
@hannni It violates KISS and "Make one thing, but make it great" principles. VSCode is editor.

**Comment by CryZe** [comment]
The Go plugin automatically downloads everything too. And how does it violate KISS? It's super simple for the user if he doesn't need to manually configure everything.

**Comment by KalitaAlexey** [comment]
You may not have rustc installed, but have VSCode.

**Comment by wycats** [comment]
> @hannni It violates KISS and "Make one thing, but make it great" principles. VSCode is editor. I am against it.

I don't understand what this means. Surely "keep it simple stupid" should mean that things more or less "just work". Asking every user of VSCode to perform a dozen steps just to get their editor working strikes me as neither "simple" nor "easy".

**Comment by steveklabnik** [comment]
Yeah, a lot of people come into `#rust-beginners` and ask about IDEs. I try to point them to RustyCode, but this kind of setup stuff is a big pain. Making it easier for new users would be awesome.

**Comment by saviorisdead** [comment]
I am not sure about this `install rust for you feature`, because you are right, there are so many ways to install and manage rust toolchain (`rustup` hopefully wil fix that), but I think ability to install all required binaries is good suggestion, will look into it.

**Comment by Draivin** [comment]
We could implement a command like "Install Dependencies" that would install all the easily installable ones (the ones that can be installed by running "cargo install ...").

**Comment by trixnz** [comment]
I've added some of this functionality in PR #163. If anyone has any suggestions before it gets merged, I'd be happy to see how we can improve it :+1:.
