### ISSUE TITLE
Rustsym Integration only works in the main folder

### ISSUE THREAD

**Issue by CryZe** [saviorisdead/RustyCode#153]
If you are working on a crate in a sub directory of your main folder, it won't find any symbols.

**Comment by saviorisdead** [comment]
Is this integration issue or `rustsym` itself?

**Comment by CryZe** [comment]
Seems like an integration issue, as it should just report the proper path to rustsym?! But I'm not 100% on that.

**Comment by CryZe** [comment]
Yeah looks like rustsym itself is capable of handling this properly.

**Comment by saviorisdead** [comment]
OK, then integration need a fix.
@trixnz tagging you to keep you informed :)

**Comment by trixnz** [comment]
Yikes, I didn't think about this use case; I generally keep my workspace root at the crate root.

The question is how to figure out the crate root from the current file being modified?

We could potentially iterate directories backwards from the currently open file until Cargo.toml is found, unless there is a more simple solution with some VSCode API?

**Comment by saviorisdead** [comment]
`The question is how to figure out the crate root from the current file being modified?`
Yes, we currently doing something similar [here](https://github.com/saviorisdead/RustyCode/blob/master/src/services/commandService.ts#L279).
But maybe VSCode has some convenient API for this case, I am not sure.

**Comment by trixnz** [comment]
Fixed it by using the `cwd()` function RustyCode already had, although I've moved it to `PathService` as it seems to be a more appropriate spot. PR is [here](https://github.com/saviorisdead/RustyCode/pull/155).
