### ISSUE TITLE
Global symbol search

### ISSUE THREAD

**Issue by danslapman** [saviorisdead/RustyCode#157]
It seems that `rustsym` allows to search for symbols in the whole crate, however 'Navigate to symbol' command searches in the current file only.

**Comment by CryZe** [comment]
CTRL+T, have fun :)

**Comment by danslapman** [comment]
`No symbols matching` and no fun :(

**Comment by trixnz** [comment]
Which version of RustyCode are you using? There was an issue in 0.15.1 where I incorrectly assumed the workspace root as being the crate root. It should be fixed in 0.16.0.

**Comment by danslapman** [comment]
I'm using 0.16.0

**Comment by trixnz** [comment]
Hmm, okay. If you run `rustsym search -g /path/to/crate/root somesymbol` from a terminal, do you see any symbols?

**Comment by danslapman** [comment]
Yes, I do
In fact, I opened this issue here just because I'm sure it's a kind of VSCode problem. It says "Open a text file first to go to a symbol"

**Comment by CryZe** [comment]
Do you not have a .rs file open? O.o

**Comment by danslapman** [comment]
When I open some .rs file, "Go to symbol" works, but only file-wide

**Comment by CryZe** [comment]
Go to symbol isn't meant to work across multiple files, if anything check "show all symbols", type something there and then it should show the symbols you searched for.

**Comment by danslapman** [comment]
"Show all symbols" doesn't show any symbols.

**Comment by trixnz** [comment]
Is `Cargo.toml` accessible from any directory from the parent folders of the rust file you're editing? Since you said `rustsym` returns symbols, it sounds like another integration issue.

When you hit Ctrl-T, we search up through the parent folders of the current file and look for `Cargo.toml`. If it can't find it, then you *should* get an error about that when you close the symbol list window.

**Comment by danslapman** [comment]
Oh, I got it. This way it works. However, there is a strange issue: I have a `pub struct Store` in my project. When I type `store`, it is founded successfully, but `Store` query shows no results.

**Comment by trixnz** [comment]
What steps did you take to fix it in case someone else stumbles upon the same issue? :smile:

Regarding the `Store` issue, I just pushed 0.2.2 of `rustsym` which fixes the case sensitivity. You can update it with cargo.

**Comment by danslapman** [comment]
@trixnz 0.2.2 works nice, thanks!
