### ISSUE TITLE
Consider more helpful message for "Racer not found"

### ISSUE THREAD

**Issue by TomasHubelbauer** [saviorisdead/RustyCode#168]
Hey, I'm willing to prepare a PR for this with some guidance required (no prior experience with VS Code plugin development), if you think this is a good idea.

https://github.com/saviorisdead/RustyCode/blob/c95ce647235147e69a5635b586da8af0406d9596/src/services/suggestService.ts#L33-L38

I think this label should have a `command` associated, one that says that:
- You need to install Racer (for people who don't read the readme)
- How to install Racer
- You should put Racer to your `PATH` (and how)
- (Possibly) What's in your `PATH` and whether Racer was detected in a default location where `cargo install racer` puts it (or even offer to open the integrated VS Code terminal and put the `cargo install` command there for you to run)

Do you think this is worth adding? I think there should be a little hand-holding (the fourth bullet) flow so people's experience with Rust development can be positive right from the start. I understand if you won't prioritize this highly, but am willing to give implementing this a shot. Let me know what you think.

**Comment by Draivin** [comment]
Just some thoughts:

There is a [pending pull request](https://github.com/saviorisdead/RustyCode/pull/163) that implements a command that installs everything that can be installed through `cargo install`.

I'm not sure about the current state of racer, but it used to require you to have other stuff set in the environment variables, such as the path to the rust source code. If we are assuming people aren't reading the readme, we should probably warn if the environment variable is not set as well.

Also, I don't know about other operating systems, but on windows all the cargo installed stuff goes to the same directory as the cargo executable itself, so if cargo is in your `PATH`, so should be racer if it is installed.

**Comment by TomasHubelbauer** [comment]
Thanks for the pointers, I might have read the ReadMe (the second time) but I still haven't searched the issues first! Shame on me. I'll go check out the PR, maybe I can help with that instead.

**Comment by TomasHubelbauer** [comment]
I'm closing this. Recently I was setting up RustyCode on a new computer and the experience is more straightforward than I though, my old setup was a little messed up because of a botched Rust install. I welcome the linked PR and still want a more streamlined experience setting RustyCode up in absence of everything it depends on, but it's less pressing than I though, that's why I decided to close this issue for now.
