### ISSUE TITLE
rustfmt does not run

### ISSUE THREAD

**Issue by mooman219** [saviorisdead/RustyCode#172]
Running RustyCode 0.18.0 and RustFMT 0.6.0 on Windows 10.

Nothing happens when running a format or enabling `"rust.formatOnSave": true` and saving. When running the command `cargo fmt` from the command line, everything formats as it should. Rusty code produces no output when it fails to format, and no temporary files are created. The file is being found because If I remove rustfmt.exe, RustyCode produces an error that it could not be found.

This is different from https://github.com/saviorisdead/RustyCode/issues/164 because I am not getting any output when it fails to run while that issue is getting a syntax error.

**Comment by CryZe** [comment]
Yeah same

**Comment by MrWolfZ** [comment]
same here

**Comment by chessnokov** [comment]
same

**Comment by ruabmbua** [comment]
Same here

**Comment by trixnz** [comment]
@saviorisdead I recommend fast tracking #173 into a new release as this is a significant issue.

**Comment by gertcuykens** [comment]
same on OSX :)
racer = ok
rustsym = ok 

cargo fmt works only manually in console, no formating on `option + shift + F`
cargo check works only manually in console, no error highlighting present in vscode

```
error: macro undefined: 'printlnn!'                                                                                                  
 --> src/main.rs:4:6                                                                                                                 
  |                                                                                                                                  
4 |      printlnn!("Hello, world!");                                                                                                 
  |      ^^^^^^^^                                                                                                                    
  |                                                                                                                                  
  = help: did you mean `println!`?                                                                                                   
                                                                                                                                     
error: aborting due to previous error                                                                                                
                                                                                                                                     
error: Could not compile `gert-test`.
```

**Comment by masaeedu** [comment]
@saviorisdead, could #173 please be merged? Formatting doesn't seem to be working with the latest version of rustfmt.

**Comment by W4RH4WK** [comment]
I am afraid @saviorisdead may be dead... no commit / merge for almost a month.

**Comment by saviorisdead** [comment]
@masaeedu @W4RH4WK No, I'm not dead yet :) It will be merged along with other PRs in coming days.

**Comment by W4RH4WK** [comment]
@saviorisdead great to hear from you, welcome back :)

**Comment by 5HT** [comment]
Guys, please merge it :+1:  <3
