### ISSUE TITLE
Linting using cargo rustc

### ISSUE THREAD

**Issue by jmquigs** [saviorisdead/RustyCode#18]
Hello,

I wanted to leave a note on linting for when somewhat gets to it :smile:   I use atom with the rust-linter package, which uses `cargo build` to do the linting.  I think a better option might be to use `cargo rustc` as described in this ticket: https://github.com/AtomLinter/linter-rust/issues/29

The problem with `cargo build` is that it does a full build.  If the program has no error, it is still building in the background.  If you tab to a console to run your program, cargo may also trigger a build there and the two can interfere with each other.  Also, atom has no indication that a lint is still in progress, so if you just fixed an error and saved (and you actually fixed it), you can end up staring at the code for a few seconds, wondering whether the error is still there, before the build completes and the UI error is removed.

Its probably better to have a lint step that is run on each save with `cargo rustc`.  That command seems to run pretty quickly.  Then the project can be actually built with a separate command (or perhaps make this a preference: build after successful lint).

Great work here, BTW!

**Comment by KalitaAlexey** [comment]
See cargo-check

**Comment by jmquigs** [comment]
It seems like cargo-check just runs `cargo rustc`.  Anyway I tested `cargo rustc` with the atom linter and it works pretty well; better than `cargo build` anyway.  The full command is `cargo rustc -Zno-trans`

**Comment by Draivin** [comment]
The latest version already has a "Cargo Check" command, which calls `cargo rustc -- -Zno-trans`.

**Comment by jmquigs** [comment]
Cool, can probably close this then.
