### ISSUE TITLE
Don't show snippets/suggestions in comments

### ISSUE THREAD

**Issue by TedDriggs** [saviorisdead/RustyCode#181]
At the moment, the following will all show full type-aware suggestions:

```
/// {CURSOR HERE}
fn foo(bar: i32) -> i32 {
}
```

```
fn foo(bar: i32) -> i32 {
    // {CURSOR HERE}
}
```

**Expected behavior:** In comments, disable suggestions. This is on 0.18.0 with the latest racer and rustfmt installs

**Comment by Gordon-F** [comment]
Looks like we can't resolve it. [VSCode issue](https://github.com/Microsoft/vscode/issues/5069)
