### ISSUE TITLE
"Rust Tools Missing" bug on Windows

### ISSUE THREAD

**Issue by boyedarat** [saviorisdead/RustyCode#186]
Updated to the latest version of Rusty Code v0.19.0 on VSCode Insider 1.7.0 (Windows 10 x86_64).
The "Rust Tools Missing" message shows up on the status bar.
The status bar also shows "Racer: On".

Is the new tools detection code using Promises, trying to find them on the PATH environment variable?
I've explicitly specified all location of tools in my settings.json. I do not want to pollute my PATH by adding all my Rust tool locations to it.

All the above are shown in the attached screen shot.
![missing_tools_bug](https://cloud.githubusercontent.com/assets/22816484/19350874/0d4c6928-918c-11e6-903f-04981020ca49.jpg)

**Comment by trixnz** [comment]
It runs two passes; the first checks if the path specified in the settings file exists, and falls back to the `PATH` in the event that it doesn't exist. You have specified all of the paths, so this shouldn't happen.

Can you upload your `settings.json` so I can run a test locally?

**Comment by trixnz** [comment]
Nevermind, was a silly error. PR issued, thanks!

**Comment by boyedarat** [comment]
Sorry for the late reply, was away the last few days.
I am still getting the same issue with v0.19.1.
I even tried reinstalling the extension but no luck.

I've attached the settings.json for your testing.
[settings.json.txt](https://github.com/saviorisdead/RustyCode/files/531889/settings.json.txt)

**Comment by boyedarat** [comment]
I did some digging and found that if the .exe extension is omitted, the "Rust Tools Missing" error shows up. The error goes away when I add the .exe extension to the tools. However. the tools work just fine in either case.

I've attached an updated settings.json for comparison with the one posted earlier.
[storage.json.txt](https://github.com/saviorisdead/RustyCode/files/531940/storage.json.txt)
