### ISSUE TITLE
Unable to configure rust tools on OS X

### ISSUE THREAD

**Issue by Joev-** [saviorisdead/RustyCode#201]
Hi,

I'm hoping that I can post this here. I'm having a lot of trouble understanding how to configure VS Code, RusyCode and the rust tools on OS X. I am using VS Code version 1.6.1 and RustyCode 0.19.1.

I have followed the instruction in the readme and have installed all tools as described using cargo. I am launching VS Code using Spotlight / Alfred. I get syntax highlighting, and can run Cargo commands using the command palette. However I am unable to make use of completion or formatting, in the status bar it says "Racer: not found". Formatting code displays an info box with "The "rustfmt" command is not available. Make sure it is installed."

I have configured my PATH to contain the path to Cargo's bin directory, and I have also added the RUST_SRC_PATH variable. I can run racer from the command line fine and get completion information. rustfmt is also available to me.

```
export PATH=~/.cargo/bin:$PATH
export RUST_SRC_PATH=~/dev/.rust/src

....
$ which rustfmt
/Users/joseph/.cargo/bin/rustfmt
$ which racer
/Users/joseph/.cargo/bin/racer
$ racer complete std::io::B
MATCH BufReader,50,11,/Users/joseph/dev/.rust/src/libstd/io/buffered.rs,Struct,pub struct BufReader<R>
MATCH BufWriter,306,11,/Users/joseph/dev/.rust/src/libstd/io/buffered.rs,Struct,pub struct BufWriter<W: Write>
MATCH BufRead,1203,10,/Users/joseph/dev/.rust/src/libstd/io/mod.rs,Trait,pub trait BufRead: Read
MATCH Bytes,1600,11,/Users/joseph/dev/.rust/src/libstd/io/mod.rs,Struct,pub struct Bytes<R>
```

I have also attempted to configure RustyCode using the provided user settings with no luck. The result is the same, Racer cannot be found, and rustfmt is reported as not being installed.

```
{
    "rust.racerPath": "~/.cargo/bin/racer",
    "rust.rustfmtPath": "~/.cargo/bin/rustfmt",
    "rust.rustLangSrcPath": "~/dev/.rust/src"
}
```

I'd really appreciate some help in getting this working. I feel like I must be missing something obvious that would prevent this from working.

Thanks.

**Comment by KalitaAlexey** [comment]
Dear @Joev-, could you change **~** to absolute path?

**Comment by Joev-** [comment]
That fixes it, thanks. Does VS Code not support tilde expansion?

**Comment by KalitaAlexey** [comment]
@Joev- I do not know. If you want you can open an issue in VSCode repository.

**Comment by kowr** [comment]
That helps, thanks!
