### ISSUE TITLE
`Cargo: Check` command doesn't highlight errors in file

### ISSUE THREAD

**Issue by drusellers** [saviorisdead/RustyCode#207]
Is that expected? I'd sure love to get some warning squiggles instead of a console dump.

**Comment by W4RH4WK** [comment]
Does running `Cargo: Check` populate the Diagnostics / Problems panel? If not, try adding `"rust.useNewErrorFormat": true,` to your config.

**Comment by drusellers** [comment]
`~/.vscode/settings.json`

```
// Place your settings in this file to overwrite default and user settings.
{
    "rust.useNewErrorFormat": true
}
```

BOOM. Great success.
