### ISSUE TITLE
Mute attributes?

### ISSUE THREAD

**Issue by drusellers** [saviorisdead/RustyCode#212]
What does this group think about giving attributes more of a muted tone? Is this the right place to ask and attempt a PR?

![image](https://cloud.githubusercontent.com/assets/63355/20137942/3399c366-a643-11e6-8aa7-fc45c4915a07.png)

I'm thinking that we just mute it a bit rather than plain white.

**Comment by W4RH4WK** [comment]
This may be the wrong place for such a change. The color displayed is determined by your selected theme. Not the Rust syntax definition.

I recommend using a custom color theme if you don't like the default one.

**Comment by drusellers** [comment]
@W4RH4WK agreed that the theme is what provides the color. So I guess the question is "Do we need a custom theme to support all of the unique aspects of Rust or not?"

**Comment by W4RH4WK** [comment]
Anyway, if you'd like to have finer grained control over how Rust code is highlighted, you should start by taking a look at the official [Rust syntax file](https://github.com/Microsoft/vscode/blob/master/extensions/rust/syntaxes/rust.json). I don't think we should add a syntax file to this extension unless it's really necessary and we couldn't add the relevant changes to the official one.

I'd strongly advice against creating a new custom *theme* just for Rust.

**Comment by drusellers** [comment]
@W4RH4WK roger that, I have no clue how all of this works - or where to even try and make my request so I started here. :) I'll take a look at the syntax file and see what it has to say about the attribute syntax.

**Comment by drusellers** [comment]
Looks like right here: https://github.com/Microsoft/vscode/blob/master/extensions/rust/syntaxes/rust.json#L212 is where attribute is defined. Now to learn how to color it differently. ;p Thank you @W4RH4WK for the pointers.

**Comment by CryZe** [comment]
This is not really the most appropriate place to talk about this, but we
should get ? operator highlighting in until the next VS Code release as
that operator will become stable on December 23rd. And as some proposed, it
would be cool if editors would highlight it in a special color that you can
immediately notice. So maybe we should work together on this.

**Comment by drusellers** [comment]
@CryZe where would be a good place to talk about this? For the `?` should we open up an issue in `vscode` for the rust.json file?

**Comment by CryZe** [comment]
Here's an image of this btw: ![Image](https://cloud.githubusercontent.com/assets/310393/18568833/1deed796-7b6d-11e6-99af-75f0d7ddd778.png)

**Comment by CryZe** [comment]
@drusellers I guess we could open an issue there, but I think it'll get much more attention by Rustaceans if we open one here (too?).

**Comment by drusellers** [comment]
@CryZe now that Rust has shipped the `?` do we want to try and get it added?
