### ISSUE TITLE
Only lib.rs correctly complete

### ISSUE THREAD

**Issue by tioover** [saviorisdead/RustyCode#215]
<img width="526" alt="2016-11-15 1 56 48" src="https://cloud.githubusercontent.com/assets/930060/20276392/04219dc8-aad7-11e6-89cc-2a289f02bfb7.png">
<img width="895" alt="2016-11-15 1 57 29" src="https://cloud.githubusercontent.com/assets/930060/20276397/0833ebfa-aad7-11e6-8b82-a5460403c580.png">
the other file can only complete std.
<img width="860" alt="2016-11-15 2 00 15" src="https://cloud.githubusercontent.com/assets/930060/20276455/44c0686e-aad7-11e6-8f5b-338f3a5092d4.png">

**Comment by W4RH4WK** [comment]
Can you provide the code, so I can directly test it?

**Comment by tioover** [comment]
Seem like other editor have a similar situation as well.
Maybe racer issue...
