### ISSUE TITLE
`cargo build` and friends don't do anything

### ISSUE THREAD

**Issue by crumblingstatue** [saviorisdead/RustyCode#22]
If I run `Cargo Build [Debug]` (or any other cargo command) from the command palette, it spawns the output saying `Running "cargo build":`, and nothing else happens. No CPU usage, no error message, nothing.

I'm using vscode 0.10.2 on Linux x86_64, cargo is installed using [multirust-rs](https://github.com/Diggsey/multirust-rs).

cargo is located in `~/.multirust/bin`, and is added to `PATH` inside `~/.profile`.
Using cargo from terminal works without problems.

Could it be that the `PATH` variable available to RustyCode disregards `~/.profile` for some reason?

Even then, RustyCode should at least issue an error message like `Couldn't execute cargo. Executable not found` instead of doing absolutely nothing.

EDIT:
I also get this error message when launching visual-studio-code:
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

This may or may not have something to do with the error.

**Comment by crumblingstatue** [comment]
If I run RustyCode in the Extension Development Host, I get this:
![](http://i.imgur.com/dXOERuf.png)

**Comment by Draivin** [comment]
Apparently it can't find the cargo executable, the vscode extensions use the environment vscode was executed in, so if cargo was in that environment, it should work.

RustyCode should probably allow a cargoPath option though.

**Comment by crumblingstatue** [comment]
I printed out the PATH environment variable inside the plugin, and it indeed seems to have ignored `.profile`. I'm not sure where else I can set `PATH` where vscode can pick it up.

If there is no way to let vscode know about custom additions to `PATH`, an issue should probably be filed on the vscode repository about that.

Anyway, the issue still stands that RustyCode should report an error message when things like this happen instead of doing nothing.

**Comment by crumblingstatue** [comment]
> Edit: could you open vscode from a terminal and see if it runs cargo fine?

Running vscode from a terminal makes no difference.

**Comment by crumblingstatue** [comment]
After many hours of fiddling with GNU/Linux environment variable management, I finally managed to have vscode pick up my PATH changes correctly. I'm not sure what fixed it, but it's good now.

However, I'm going to leave this issue open due to RustyCode silently ignoring a missing cargo.

**Comment by saviorisdead** [comment]
Yes, option to specify cargo path sounds like a good idea.

**Comment by saviorisdead** [comment]
Messages about missing executables implemented by @Draivin 
`rust.cargoPath` is on it's way :)
