### ISSUE TITLE
Closing the `cargo run` window should kill/ask-to-kill the process

### ISSUE THREAD

**Issue by arthurprs** [saviorisdead/RustyCode#23]
Closing the `cargo run` window should kill/ask-to-kill the process. Right now it leaves the process running on the background and you must kill it using the terminal.

**Comment by Draivin** [comment]
I don't think vscode has a listener for this, we could do as the debugger service and provide a command "terminate cargo process".

**Comment by arthurprs** [comment]
If that's the case we should probably open an issue on their repo.

**Comment by Draivin** [comment]
As of version 0.5.1, RustyCode has a `Cargo: Terminate Running Task` command that stops the currently executing cargo task. Also, when you run any cargo command it will automatically terminate a previous command if it is still running.
