### ISSUE TITLE
New src path setting for Racer?

### ISSUE THREAD

**Issue by canfoderiskii** [saviorisdead/RustyCode#232]
Anyway, thanks for the wonderful extension at first.

Any possible to add new setting for Rust source path so that the Racer can find it without setting the system environment variable RUST_SRC_PATH?

Maybe in this way, I can re-direct racer to different version of Rust for different projects.

**Comment by KalitaAlexey** [comment]
Hi @canfoderiskii,

You can. Click on the File->Settings->Workspace Settings. It is workspace settings.
Add "rust.rustLangSrcPath".
Since that moment, when you open this workspace racer will use specific value.

**Comment by canfoderiskii** [comment]
@KalitaAlexey Thank you so much, it works fine. I'll close this issue.
