### ISSUE TITLE
Will Linting be added to the Roadmap? 

### ISSUE THREAD

**Issue by xialvjun** [saviorisdead/RustyCode#233]
I think linting is a very important tool for the rust beginers (to fight against the borrow checker?).

Hope you think about it.

**Comment by KalitaAlexey** [comment]
What do you exactly mean? What should the linting do?

**Comment by xialvjun** [comment]
Just like the picture in [Rust Enhanced for Sublime Text](https://packagecontrol.io/packages/Rust%20Enhanced)

![Linting for Rust](https://packagecontrol.io/readmes/img/fbd92951a9feb72954f04eff621fa879248722e8.gif)

In it, when we save our code, the extension will give us the errors soon without compile. Wait for compiling is a little slower, specially when the project is big.

**Comment by KalitaAlexey** [comment]
In RustyCode there is a parameter "checkOnSave". It solves what you want.

**Comment by xialvjun** [comment]
Oh, yes, that's it. Sorry I didn't see it. And thanks.

**Comment by KalitaAlexey** [comment]
If it is what you wanted, close the issue, please.
