### ISSUE TITLE
Specify cargo features on a session-by-session basis?

### ISSUE THREAD

**Issue by radix** [saviorisdead/RustyCode#239]
I realize that there's a user setting for specifying feature flags, but when I'm working on a library with features I often want to switch back and forth between testing with and without features. It'd be nice if there were a quick way to open up a features list and toggle them on and off.

**Comment by KalitaAlexey** [comment]
@radix,
Check out my repo: https://github.com/KalitaAlexey/vscode-rust
I have a feature named "custom configurations".

**Comment by radix** [comment]
@KalitaAlexey I'm a bit confused by that project. Is it a fork of RustyCode? Is RustyCode unmaintained or something? Why is the README nearly identical? It'd be nice to clarify the relationship of these two packages.

**Comment by KalitaAlexey** [comment]
@radix,
Please look at https://github.com/KalitaAlexey/vscode-rust/issues/40
