### ISSUE TITLE
Auto-complete doesnt work?

### ISSUE THREAD

**Issue by nambrot** [saviorisdead/RustyCode#240]
I just installed RustyCode with all the dependencies (`racer`, `rustfmt`, etc.) Added it the PATH.

However, I can't get the auto-complete to work. Am I missing an obvious configuration step?

**Comment by KalitaAlexey** [comment]
Hi @nambrot,
This extension is no longer maintained.
Please look at https://github.com/KalitaAlexey/vscode-rust

**Comment by KalitaAlexey** [comment]
@nambrot,
You can install it from marketplace. It's name "Rust".

**Comment by nambrot** [comment]
Thanks @KalitaAlexey, opened an issue at https://github.com/KalitaAlexey/vscode-rust/issues/64
