### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by amilajack** [saviorisdead/RustyCode#243]
Would be nice if some installation instructions could be included :)

**Comment by KalitaAlexey** [comment]
Hi @amilajack,
The repository is obsolete and unmaintainable.
Take a look at https://github.com/editor-rs/vscode-rust

**Comment by amilajack** [comment]
@KalitaAlexey thanks! should I pr to add a deprecation notice to the readme?

**Comment by KalitaAlexey** [comment]
@amilajack,
The maintainer will not respond.
I am sorry.
