### ISSUE TITLE
go to definition for standard library

### ISSUE THREAD

**Issue by simbo1905** [saviorisdead/RustyCode#245]
I installed everything from within Visual Studio Code (no manual installation elements) and code completion works great for the code in my project. 

If I try to "go to definition" of something like `std::cmp::Ordering` it says "No definition found for Ordering". 

Yet on the console within visual studio code if I type `racer complete std::cmp::Ordering` I get a MATCH showing `public enum Ordering`. 

I ran `rustup component add rust-src` in the VSC console as per the racer docs but it said `info: component 'rust-src' is up to date`. 

Is there anything I need to do to get this to work or is this feature not yet implemented?

**Comment by KalitaAlexey** [comment]
This extension is no longer maintained.
Please install https://github.com/editor-rs/vscode-rust
