### ISSUE TITLE
Focus must not be changed to output panel after build

### ISSUE THREAD

**Issue by KalitaAlexey** [saviorisdead/RustyCode#26]
Focus changes. It is weird and uncomfortable.

**Comment by KalitaAlexey** [comment]
https://github.com/Microsoft/vscode/issues/876

**Comment by BusyJay** [comment]
Just tested with VS code 1.0, it seems work as expect.

**Comment by KalitaAlexey** [comment]
Yes. This is fixed in VSCode 1.0
