### ISSUE TITLE
Ability to restart racer process after it has stopped

### ISSUE THREAD

**Issue by crumblingstatue** [saviorisdead/RustyCode#28]
Racer is pretty buggy, and it stops often for various reasons.

It looks like once it has stopped, it's not restarted until you restart vscode itself.

Since this happens pretty often, it's very damaging to the workflow having to restart vscode every minute or so.

Either racer should be restarted automatically when it fails, or at least a `Restart racer` command should be given to the user for cases like this.

**Comment by Arrem** [comment]
Just came here to suggest the idea myself. Automatic restarts would be perfect, since I get quite a few crashes.

**Comment by saviorisdead** [comment]
Automatic restarts are now possible :) Thanks to @Draivin
