### ISSUE TITLE
RustyCode tasks should register keybindings

### ISSUE THREAD

**Issue by EdorianDark** [saviorisdead/RustyCode#32]
RustyCode should register some common commands as key bindings like for example:
```
    "keybindings": [
    {
        "command": "rust.cargo.run.debug",
        "key": "Ctrl+Shift+B"
    },
   {
        "command": "rust.cargo.test",
        "key": "Ctrl+Shift+T"
   }]
```
in the contributes section of package.json

**Comment by Draivin** [comment]
To whoever implements this, remember to add `"when": "editorLangId == 'rust'"` to the shortcuts.
