### ISSUE TITLE
Cargo tasks - wrong folder on build

### ISSUE THREAD

**Issue by jaxx** [saviorisdead/RustyCode#34]
Cargo tasks use Visual Studio Code application folder when I want to build my project. I guess when building project it must be done in project folder instead.

![capture](https://cloud.githubusercontent.com/assets/723258/11458944/8c243cb2-96d3-11e5-9937-4f5fd60976e2.PNG)

**Comment by saviorisdead** [comment]
Hi there :)
Can you provide more information? Like, layout of your project's folder structure and such :)

**Comment by jaxx** [comment]
I have very basic structure of project - structure like ```cargo --new bin``` creates. My rust projects folders is in C: root. If I open this project file main.rs in VSCode and try to compile it - it gives an error as seen on picture above.
```
C:
|__ rust_projects
    |__ test_project
        |__ Cargo.toml
        |__ Cargo.lock
        |__ src
            |__ main.rs
```
Operating system Windows 10 64-bit.

**Comment by saviorisdead** [comment]
Hmm, I think you need to open `test_project` folder in VSCode, so then `vscode.workspace.rootPath` will contain correct path. Please, try this and let me know.

**Comment by jaxx** [comment]
Yup, if I open the folder instead of file, path is correct and project compiles.

**Comment by saviorisdead** [comment]
Happy to help. :)

**Comment by jaxx** [comment]
Thanks :) :+1:
