### ISSUE TITLE
Rust debugging?

### ISSUE THREAD

**Issue by egamma** [saviorisdead/RustyCode#37]
Great progress on the Rust support!

I suggest to also consider implementing integrated debugging of Rust within Code.
Here are some starting points:
- https://code.visualstudio.com/docs/extensions/example-debuggers
- https://code.visualstudio.com/docs/extensionAPI/api-debugging

**Comment by saviorisdead** [comment]
It is definitely in our field of view. I'll add it to roadmap. Thank you for bringing this up.

**Comment by aka-demik** [comment]
[Native debug](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) extension can debug with GDB and LLDB.
I think it will be able to debug and rust-application.

**Comment by CryZe** [comment]
Yeah, this extension works perfectly fine with Rust (even with pretty formatting).
