### ISSUE TITLE
"The racer process has stopped" with empty error output

### ISSUE THREAD

**Issue by dikaiosune** [saviorisdead/RustyCode#38]
Just wanted to first say, really happy this exists, and if I can help I'd be glad to (although no experience with TypeScript).

I installed 0.4.4 today from the gallery, got everything configured (relevant config sections below), but when I restarted VSCode a bar appeared at the top of the screen:

`Info | The racer process has stopped. | View Error | Close`

When I click on View Error, this shows in the output pane:
```
Last command: 

Racer Error: 
```

When I click Close, the bar disappears for about half a second and then re-appears. Still no error information available if I click View Error after it re-appears.

Here's the relevant portion of my user preferences:

```
	"rust.cargoPath": "/usr/bin/cargo",
	"rust.racerPath": "/usr/bin/racer",
	"rust.rustLangSrcPath": "/usr/src/rust/src",
	"rust.rustfmtPath": "/home/adam/.cargo/bin/rustfmt"
```

Racer works just fine from the command line, and I'm also able to use auto-completion in Atom (albeit it's pretty slow). My RUST_SRC_PATH environment variable is set to the same path as the setting I copied above. I'm running Arch Linux with VSCode version 0.10.2.

After deleting the plugin directory and compiling from the repo, I can replicate this behavior on a freshly built copy running in the Extension Development Host, also with empty error logging in the error panel. There doesn't appear to be any errors reporting in the Debug Console either (although this is my first time firing up VSCode extension debugging, so I don't really know what I'm doing).

Since I'm unfamiliar with the codebase I'm not sure where I should start with the error logging, although I'm going to continue poking through to see if I have an a-ha moment. What other information can I provide to help track this down?

**Comment by Draivin** [comment]
Hmm, in `suggestService.ts` at line 94, you could try putting a breakpoint there and checking what the variable `error` in the scope is at that point.

**Comment by dikaiosune** [comment]
Thanks for the very fast reply and the tip. I added some breakpoints there, and `stopDaemon` returns before it get's to line 94 because `racerDaemon` is null and that very first if clause is triggered. Looking through the remainder of the variables, it looks like the daemon wasn't ever instantiated. Here's the contents of `lineBuffer`:

```
[0]: "Sorry, I didn't understand command daemon"
[1]: "usage: /usr/bin/racer complete linenum charnum fname [substitute_file]"
[2]: "or:    /usr/bin/racer find-definition linenum charnum fname [substitute_file]"
[3]: "or:    /usr/bin/racer complete fullyqualifiedname   (e.g. std::io::)"
[4]: "or:    /usr/bin/racer prefix linenum charnum fname"
[5]: "or replace complete with complete-with-snippet for more detailed completions."
```

I think maybe my racer install is out of date? Installed fairly recently and I thought daemon was added a while ago. Going to try updating racer and report back.

**Comment by dikaiosune** [comment]
OK, rebuilt racer from git and it's working now. Maybe it'd be good to include some version dependency information in the README? Or some error logging for a null `racerDaemon` instance with a suggestion to update?

Thanks again for your help.

**Comment by Draivin** [comment]
Glad to be of help, I still can't understand the null `racerDaemon` though, since for it to show the error message that you reported it needs to get to the end of the `stopDaemon` function, in theory the only case when it hits the null if branch is after the daemon has already been closed once.

**Comment by dikaiosune** [comment]
I see -- if it'd help it shouldn't be too much work to downgrade to the version with the problem (it's from an outdated package in the Arch User Repos). Let me know if you're interesting in pursuing and I'll switch back to try the debugging again.

**Comment by Draivin** [comment]
No need to, but thanks for the offer, later I will try downloading an old version of racer so I can find a more user friendly way to report a missing daemon command.

**Comment by saviorisdead** [comment]
Problem with using pinned version of racer is racer project not using semver. It's 1.0 and that's it. I guess we could add `Help` section to README.md and suggest to update racer.
