### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by Draivin** [saviorisdead/RustyCode#4]
I would be glad if you could add a licensing header to the `suggestService.ts` file. In any case, as the scope of your project is bigger than mine, and already includes all of racer capabilities, I will update my README to point to your repository.

Header example:
```
/*
 * Copyright (c) 2015 "draivin" Ian Ornelas and other contributors.
 * Licensed under MIT (https://github.com/Draivin/vscode-racer/blob/master/LICENSE).
 */
```

**Comment by saviorisdead** [comment]
I've added license, thanks for reminding.
