### ISSUE TITLE
Lack of highlighting

### ISSUE THREAD

**Issue by KalitaAlexey** [saviorisdead/RustyCode#44]
```
impl A for B where C: D
{
    fn func() {
        assert!(1 < 2, "");
        Node::reset_child_index(child);
        self.children.remove(index);
    }
}
```
To restore hightlighting `<` must be changed with something or `where C: D` must be removed. I'd like to help, but I dont' know how to fix highlighting

**Comment by saviorisdead** [comment]
Right now Rusty Code uses built-in highlighting, so I should open issue in VScode repo.
