### ISSUE TITLE
Racer error every few minutes

### ISSUE THREAD

**Issue by fuchsnj** [saviorisdead/RustyCode#48]
rust stable 1.5 / Windows 10

code completion seems to work, but every few minutes this error pops up. After dismissing it continues to work.
```
Last command: 
complete-with-snippet 50 -1 c:\Users\nathan\repos\program_name\src\file.rs C:\Users\nathan\AppData\Local\Temp\tmp-9576Sj9wVh3anPK7.tmp

Racer Output: 
error: 'c:\Users\nathan\repos\program_name\src\file.rs ' isn't a valid value
USAGE:
	racer complete-with-snippet <fqn>
	racer complete-with-snippet <linenum> <charnum> <path> [substitute_file]
Please re-run with --help for more information
Racer Error: 
Racer Output: 
error: 'c:\Users\nathan\repos\program_name\src\file.rs ' isn't a valid value
USAGE:
	racer complete-with-snippet <fqn>
	racer complete-with-snippet <linenum> <charnum> <path> [substitute_file]
Please re-run with --help for more information
Racer Error: 

```

**Comment by Draivin** [comment]
Do you have a way to reproduce this? that -1 column number is really strange, I can put bound checks on the command triggers, but I would like to know the cause.

**Comment by fuchsnj** [comment]
I will try to get a simple case to reproduce it. So far it seems fairly random.

**Comment by nikonthethird** [comment]
If I slowly type the following invalid code into Visual Studio Code, the Racer error appears:

    fn main {
        let t = "".();
    }

If it doesn't appear right away, try removing and adding the parentheses again.

This is the error I get:

```
Last command: 
complete-with-snippet 135 -1 /home/nikon/Documents/Testing/euler3/src/main.rs /tmp/tmp-23302salenBkuEKqh.tmp

Racer Output: 
[1;31merror: '/home/nikon/Documents/Testing/euler3/src/main.rs' isn't a valid value
USAGE:
	racer complete-with-snippet <fqn>
	racer complete-with-snippet <linenum> <charnum> <path> [substitute_file]
Please re-run with --help for more information
Racer Error: 
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
```

**Comment by henriiik** [comment]
I'm having the same problem with "," it appears if you type a comma in a line without an opening parens.

![racer2](https://cloud.githubusercontent.com/assets/392416/11808777/e9c895d8-a322-11e5-9189-d04ad00e3226.PNG)
![racer1](https://cloud.githubusercontent.com/assets/392416/11808778/e9ca1d7c-a322-11e5-8f0d-7deb9e427a4d.PNG)

**Comment by saviorisdead** [comment]
I'll look into it.

**Comment by saviorisdead** [comment]
New version is out, please update extension and let me know if i fixed this issue or not :)

**Comment by henriiik** [comment]
The fix remove the crash for me :+1:

**Comment by nikonthethird** [comment]
Yeah, it seems OK for me too :+1: Awesome!

**Comment by fuchsnj** [comment]
Looks like it has been fixed for me. Thanks.
