### ISSUE TITLE
cargo build does not parse errors on failed build

### ISSUE THREAD

**Issue by henriiik** [saviorisdead/RustyCode#50]
Hello!

When i run the cargo build debug command and the build fails, the output is not parsed and the errors are not displayed and an error message is displayed instead.

Would you be interested in a pull requests that changes this behaviour?

![screen shot 2015-12-14 at 19 47 19](https://cloud.githubusercontent.com/assets/392416/11790389/ca1510d6-a29b-11e5-9a69-341ff4fa3124.png)

**Comment by saviorisdead** [comment]
Hello :)
Sure, pull requests are very welcome

**Comment by henriiik** [comment]
Okay!
