### ISSUE TITLE
How about to remove commands for different build type?

### ISSUE THREAD

**Issue by KalitaAlexey** [saviorisdead/RustyCode#55]
There are commands for Debug and for Release. I want to command take type from configuration? I can implement it. Is anyone against it?

**Comment by saviorisdead** [comment]
I actually think what it is convenient to have different commands for different build types. With configuration option you are limiting youself to only one active option.

**Comment by KalitaAlexey** [comment]
@saviorisdead Currently we have shortcuts and build on save. You build using same build type often and sometimes build using another build type. If you want to build using another build type then it can be changed in configuration.

**Comment by saviorisdead** [comment]
I think we'll leave separate commands right now as it is. We could provide a command for a custom build if somebody needs that.
