### ISSUE TITLE
Cant get it to work on windows

### ISSUE THREAD

**Issue by jeffwllms** [saviorisdead/RustyCode#57]
I have everything set up.  I set the Src path in the user settings.  Pretty sure this is right as if I change it, it errors saying racer cant find source.  I do seem to have the cargo commands.  but I cant get go-to or auto completions to work.

Any ideas, I don't seem to be getting any errors.

**Comment by saviorisdead** [comment]
Please provide more information about your workflow. Are you editing your code as project or as single file? Also, please make sure to update `racer` to latest version via `cargo install racer`.

**Comment by Draivin** [comment]
The racer crate isn't updated all that often, the correct way to install the most up to date version is `cargo install --git 'https://github.com/phildawes/racer.git'`.

**Comment by jeffwllms** [comment]
I am just testing with a single file.  I have not opened a project.  I did just install racer today as part of the process of installing the extension.  I used the method Draivin mentioned to install.  cargo install racer failed for me.

**Comment by saviorisdead** [comment]
Oh, autocompletion works on project-level only. So you need to open project in VSCode. I think we should update to it be more clear about that.

**Comment by jeffwllms** [comment]
Sorry for the late response.  Tis does seem to be what the issue was.  Just needed to have a project.

Thanks
