### ISSUE TITLE
Racer complete-with-snippet error: "isn't a valid value" on Windows

### ISSUE THREAD

**Issue by not-omer** [saviorisdead/RustyCode#67]
I'm on Windows 8.1.
I've set up RustyCode and mostly everything works fine, except for when I try to use the autocomplete feature. When I do, I'm met with "the racer process has stopped" and the following error message:

```
Last command: 
complete-with-snippet 3 8 c:\Users\Not Omer\rust\test\src\test.rs C:\Users\NOTOME~1\AppData\Local\Temp\tmp-26640ZNoxtmCHa80S.tmp

Racer Output: 
error: 'C:\Users\NOTOME~1\AppData\Local\Temp\tmp-26640ZNoxtmCHa80S.tmp' isn't a valid value
USAGE:
	racer complete-with-snippet <fqn>
	racer complete-with-snippet <linenum> <charnum> <path> [substitute_file]
Please re-run with --help for more information
Racer Error: 
```

This leads me to believe that I should try running the command after dropping the substitute_file portion, and so I do, but I'm still met with this error:

```
racer complete-with-snippet 3 8 c:\Users\Not Omer\rust\test\src\test.rs  
ERROR:racer::core: read_file couldn't open "Omer\\rust\\test\\src\\test.rs". Returning empty string  
PREFIX 4,8,foun  
thread 'searcher' panicked at 'index 9 out of range for slice of length 0', ../s  
rc/libcore\slice.rs:513  
ERROR:racer: Search thread paniced: Any  
END
```

This seems to coincide with [this issue](https://github.com/saviorisdead/RustyCode/issues/45). However, I'm running the latest version of racer, rust, and VS Code.

**Comment by not-omer** [comment]
My user settings:

```
{
    "rust.racerPath": null, // Specifies path to Racer binary if it's not in PATH
    "rust.rustLangSrcPath": "C:/rust-master/src", // Specifies path to /src directory of local copy of Rust sources
    "rust.rustfmtPath": null, // Specifies path to Rustfmt binary if it's not in PATH
    "rust.cargoPath": null, // Specifies path to Cargo binary if it's not in PATH
    "rust.formatOnSave": false, // Turn on/off autoformatting file on save (EXPERIMENTAL)
    "rust.checkOnSave": false // Turn on/off cargo check project on save (EXPERIMENTAL)
}
```

My racer, rustfmt, and cargo binaries are on my PATH.

**Comment by Draivin** [comment]
Duplicate of https://github.com/saviorisdead/RustyCode/issues/45, caused by old versions of racer not handling white space in file paths, the latest versions of racer support it, but it is not yet implemented on RustyCode.

@saviorisdead Would you mind if I broke backwards compatibility with old racer verions? It would make it a lot simpler to support the new features of racer.

**Comment by saviorisdead** [comment]
@Draivin Go ahead, I think it's time to do it. I'll update the documentation to explicitly say that we support only latest versions of Racer.

**Comment by not-omer** [comment]
So would the solution be for me to update racer? As far as I understand, I have the latest version of racer installed.

**Comment by Draivin** [comment]
Rusty Code did not support the somewhat recent feature of racer that allowed space in path names, as soon as #69 is merged this should be fixed.

**Comment by saviorisdead** [comment]
Hi :)
Try to update `Rusty Code` and `racer`. It should be fixed :)

**Comment by not-omer** [comment]
Uninstalling and reinstalling 'Rusty Code' fixed it. Thank you! Closed.
