### ISSUE TITLE
The racer process has stopped.(Again)

### ISSUE THREAD

**Issue by peng1999** [saviorisdead/RustyCode#68]
Hello! I recived the infomation `The racer process has stopped.` every time when I edit Rust source file.
This is from output:
```
Last command: 
complete-with-snippet 17 28 d:\pgw\My Web Sites\program\Rust\Posts\src\rust\src\lib.rs C:\Users\pgw10\AppData\Local\Temp\tmp-90244z0MgWOHXXL3.tmp

Racer Output: 

Racer Error: 
error: Found argument 'C:\Users\pgw10\AppData\Local\Temp\tmp-90244z0MgWOHXXL3.tmp', but complete-with-snippet wasn't expecting any

USAGE:
	racer complete-with-snippet <fqn>
	racer complete-with-snippet <linenum> <charnum> <path> [substitute_file]

For more information try --help
```
It seems that the blank space from folder name `My Web Sites` makes the mistake. Maybe it can be fixed by adding quotes?

**Comment by saviorisdead** [comment]
Hi, I think it's related to #45 and #67.
Try updating racer first.

**Comment by saviorisdead** [comment]
Hi :)
Please, update `Rusty Code` and `racer`. It should be fixed.

**Comment by peng1999** [comment]
Thanks! I updated `Rusty Code` and it works now.
