### ISSUE TITLE
Publish symbols to enable VSCode symbol-based navigation

### ISSUE THREAD

**Issue by icorderi** [saviorisdead/RustyCode#71]
**VSCode** allows you to go-to/search for _symbols_ with the `@` sign.

It would be nice if this feature was available for Rust, allowing us to go directly to a method/struct definition.

I believe **racer** is capable of generating this information.

**Comment by Soaa-** [comment]
I just had a look at racer's source, and it seems that it's not really designed to index a codebase and its symbols. Implementing this would require either adding that functionality to racer or indexing the project source within RustyCode itself.

**Comment by kikokikok** [comment]
might be worth looking at https://github.com/RustDT/Rainicorn I think it's what you're looking for.

**Comment by icorderi** [comment]
@saviorisdead what's the reason for closing the issue? 
Can we reach out to the **racer** folks and try to get support built for this?

**Comment by poidl** [comment]
It would be great to have this feature. In Atom there is a package which uses ctags (symbols-tree-view -- it's not great for Rust, but much better than nothing). Don't know if that works in vscode?

**Comment by aka-demik** [comment]
:+1: It would be great to have this feature. Reopen plz.
