### ISSUE TITLE
Fix `cargo *` commands to find .toml from the file parents instead of workspace

### ISSUE THREAD

**Issue by icorderi** [saviorisdead/RustyCode#72]
When one has multiple crates opened on the workspace the **.toml** is searched from the _$workspace_ up in the path, instead of from the current opened file.

This causes workspaces that look like the following to not be able to use _Cargo_ commands:
```
$ workspace
    | crate1
        | src
            | lib.rs
        | Cargo.toml
    | crate2
        | src
            | lib.rs
        | Cargo.toml     
```

The expected behavior from running `> cargo build` on _VSCode_ while having `crate1/src/lib.rs` as current file is to run `cargo build` on **crate1**.

The current output is:
```
Running "cargo build":
could not find `Cargo.toml` in `/Users/me/git/workspace` or any parent directory

"cargo build" completed with code 101
It took approximately 0.316 seconds
```

**Comment by KalitaAlexey** [comment]
It makes sense. I will do it.

**Comment by saviorisdead** [comment]
Hi!
@KalitaAlexey implemented it and this feature should available in the next release.

**Comment by icorderi** [comment]
Yea it's working on `vs 1.0.0` and `rusty 0.12.0`
Great job @KalitaAlexey!
