### ISSUE TITLE
Completion randomly fails on Windows

### ISSUE THREAD

**Issue by daiheitan** [saviorisdead/RustyCode#77]
RustyCode randomly do not popup any suggestion, while `racer` is still available in `PATH`

Currently only observed on Windows. Both `racer` and `rusty-code` the newest version.

One way to make it work again is to go to user settings, remove `racer path` config, save (Rusty code
will popup an error saying it could not find racer). Then restore the previous `racer path` config and save. Then the auto-completion feature will work again.

VSCode output window has no error logged.

Sorry I could not provide any further details as I have no clue what caused this problem.

**Comment by Draivin** [comment]
RustyCode should have a racer process running at all times, could you check if the racer proccess is still running the next time it fails giving a suggestion?

**Comment by daiheitan** [comment]
Yes, the process is still there. But as the Memory `racer.exe` used never changed after suggestion failed, I suppose that the process just hang up.

**Comment by Draivin** [comment]
Next time it stops, can you open developer tools (`Help > Toggle Developer Tools`), trigger a completion and check if any error appears?

**Comment by daiheitan** [comment]
No error logged.
In fact, I found a way to trigger the problem:

- Install `iron`
- Open a rust file, input `iron::`
- Select the first suggestion, which is `AfterMiddleware`
- Continue to input `::`, now the text will be: `iron::AfterMiddleware::`
- `Backspace` until `iron::`
- now input anything and no suggestion any more

**Comment by Draivin** [comment]
I tried reproducing the error but wasn't able to, I am still able to see and trigger suggestions after following the steps. I don't know how I can help you solve the problem as it is.

**Comment by daiheitan** [comment]
All right....

Maybe adding something like timeout to RustyCode may work? If racer fails to give a suggestion after the timeout, RustyCode could restart the racer process.

**Comment by daiheitan** [comment]
Also noticed that along with racer suggestions, normal VSCode suggestions are also not showing. Usually in vscode `0.10.8`, the editor will suggest a word if you type it the second time. (E.g, if I input `let a_word:i32 = 1; a`, the editor will suggest `a_word`, after the racer failure, this feature is also not working.

**Comment by peschkaj** [comment]
Tested this myself with:

- rust 1.7.0
- racer 1.2.6
- VS Code 0.10.11
- RustyCode 0.11

With the following limited program, auto-completion is not present, but only for Iron crates. Use of the rust stdlib works correctly.

```
extern crate iron;
use iron::prelude::*;
use iron::status;

fn main() {
    // your code goes here
    println!("Hello, world!");
}
```

However, racer autocomplete fails on the command line as well:

```
D:\src\peschkaj\testcc [master +4 ~0 -0 !]
λ racer complete std::io::B
MATCH BufReader,48,11,D:\src\rustc-1.7.0\src\libstd\io\buffered.rs,Struct,pub struct BufReader<R> {
MATCH BufWriter,300,11,D:\src\rustc-1.7.0\src\libstd\io\buffered.rs,Struct,pub struct BufWriter<W: Write> {
MATCH BufRead,1277,10,D:\src\rustc-1.7.0\src\libstd\io\mod.rs,Trait,pub trait BufRead: Read {
MATCH Broadcast,1507,11,D:\src\rustc-1.7.0\src\libstd\io\mod.rs,Struct,pub struct Broadcast<T, U> {
MATCH Bytes,1650,11,D:\src\rustc-1.7.0\src\libstd\io\mod.rs,Struct,pub struct Bytes<R> {

D:\src\peschkaj\testcc [master +4 ~0 -0 !]
λ racer complete Iron::n

D:\src\peschkaj\testcc [master +4 ~0 -0 !]
```
The second command should at least provide `Iron::new` - could this be an issue with racer?

**Comment by saviorisdead** [comment]
I'll close this, as this is mostly racer issue.
