### ISSUE TITLE
"The racer process has stopped."; "didn't understand command --interface=tab-text" on Windows

### ISSUE THREAD

**Issue by disportium** [saviorisdead/RustyCode#89]
Visual Studio Code gives the following message when an empty Rust source file is opened:

"The racer process has stopped."  Clicking on View Error gives the following information:

```
Last command: 

Racer Output: 
Sorry, I didn't understand command --interface=tab-text
usage: racer complete linenum charnum fname [substitute_file]
or:    racer find-definition linenum charnum fname [substitute_file]
or:    racer complete fullyqualifiedname   (e.g. std::io::)
or:    racer prefix linenum charnum fname
or replace complete with complete-with-snippet for more detailed completions.
or:    racer daemon     - to start a process that receives the above commands via stdin
Racer Error: 
```

Rusty Code settings are as follows (user settings):

```
{
    "rust.racerPath": null, // Specifies path to Racer binary if it's not in PATH
    "rust.rustfmtPath": null, // Specifies path to Rustfmt binary if it's not in PATH
    "rust.rustLangSrcPath": "C:/Program Files/Rust stable GNU 1.7/rust-master/src", // Specifies path to /src directory of local copy of Rust sources
    "rust.cargoPath": null, // Specifies path to Cargo binary if it's not in PATH
    "rust.formatOnSave": false, // Turn on/off autoformatting file on save (EXPERIMENTAL)
    "rust.checkOnSave": false, // Turn on/off `cargo check` project on save (EXPERIMENTAL)
    "rust.checkWithClippy": false // Turn on/off `cargo clippy` project on save (EXPERIMENTAL) (cargo-clippy should be installed)
}
```

Racer, rustfmt and cargo are in the PATH variable.

Rusty Code 0.11.0
Visual Studio Code 0.10.10
Racer 1.2.6
Rust 1.7
Windows 10

**Comment by se77en** [comment]
Same issue to me on Mac OSX

**Comment by Draivin** [comment]
That seems to be an old racer version, in both cases, the racer output format isn't even like that anymore. Be sure that your racerPath is pointing to the most recent version of racer.

**Comment by disportium** [comment]
Turns out there was an old version of racer installed in C:\Program Files\racer, installed six months ago by an older cargo, I imagine, since the new racer binary is installed in C:\Users\<username>\.cargo\bin

Both paths were in the PATH variable, and the older racer binary was run.

After removing the C:\Program Files\racer path from the PATH variable everything is working fine.

Thanks for your help!
