### ISSUE TITLE
Auto-Completion does not work on external Cargo dependencies others than std::

### ISSUE THREAD

**Issue by kikokikok** [saviorisdead/RustyCode#92]
I've been trying to use RustyCode with the auto-completion on external cargo dependencies without success. It doesn't seem to be a Racer Issue because Racer is able to resolve and auto-complete most of the external cargo deps on Emacs which is using the same mechanism.

**Comment by Emilgardis** [comment]
Same issue here, won't autocomplete extern crates.

**Comment by saviorisdead** [comment]
Hi there!
Please add `racer` to your `PATH` variable and try following command:
`racer complete $LINE_NUMBER $CHAR_NUMBER $PATH_TO_FILE` and dump output here.
Sometimes it gets tricky with racer and external dependencies.
Also, by any chance, are you using something like `rustup` or `multirust`?
Then, setting `export CARGO_HOME=$HOME/.cargo` might help.

**Comment by kikokikok** [comment]
That's what I was going to say. If using multirust-rs like I do we need to have the CARGO_HOME=$HOME/.cargo set. 
The remaining issues are on racer.
