### ISSUE TITLE
My extension doesn't run when I run it in debugger. It says "Extension did not start in 10 seconds".

### ISSUE THREAD

**Issue by egamma** [saviorisdead/RustyCode#96]
_From @KalitaAlexey on April 16, 2016 5:2_

- VSCode Version: 1.0
- OS Version: Ubuntu 14.04.3 x64

Steps to Reproduce:

1. Install VSCode for insiders. Uninstall VSCode for insiders. Install VSCode 1.0
2. Try run extension

Extension: https://github.com/saviorisdead/RustyCode

_Copied from original issue: Microsoft/vscode#5375_

**Comment by KalitaAlexey** [comment]
I have figured out how to fix that. I just purge everything related to vscode and install vscode.

**Comment by KalitaAlexey** [comment]
@egamma Close it.

**Comment by egamma** [comment]
Closing as requested
