### ISSUE TITLE
Is RustyCode still active or not ?

### ISSUE THREAD

**Issue by kikokikok** [saviorisdead/RustyCode#98]

**Comment by Draivin** [comment]
It seems the owner disappeared and is not accepting any pull requests or making any changes.

**Comment by KalitaAlexey** [comment]
I had chat with him. He said he was busy, but he will be back in one-two weeks.

**Comment by saviorisdead** [comment]
Yeah, I am here. My offline life got in a way, but its all good now, so no worries.
