### ISSUE TITLE
RustFmt onSave not working

### ISSUE THREAD

**Issue by conikeec** [saviorisdead/RustyCode#99]
Upgraded to the new version and formatOnSave is not working as yet.
I have rustfmt installed and it does not seem to get triggered on a save action.

I applied the following settings both in user and workspace perspective and it still ain't working
Racer and RustFmt are in PATH

{
    "rust.racerPath": null, // Specifies path to Racer binary if it's not in PATH
    "rust.rustLangSrcPath": null, // Specifies path to /src directory of local copy of Rust sources
    "rust.rustfmtPath": null, // Specifies path to Rustfmt binary if it's not in PATH
    "rust.cargoPath": null, // Specifies path to Cargo binary if it's not in PATH
    "rust.formatOnSave": true, // Turn on/off autoformatting file on save (EXPERIMENTAL)
    "rust.checkOnSave": false, // Turn on/off `cargo check` project on save (EXPERIMENTAL)
    "rust.checkWithClippy": false // Turn on/off `cargo clippy` project on save (EXPERIMENTAL) (cargo-clippy should be installed)
}

**Comment by saviorisdead** [comment]
Hi!
Please try to explicitly specify path to `rustfmt` binary in settings and let me know if something changes.

**Comment by eldyer** [comment]
Confirmed, formatOnSave doesn't seem to work, even with explicitly specified path. I'm on OS X 10.11.

**Comment by conikeec** [comment]
I confirm that it does not work.

**Comment by saviorisdead** [comment]
I'm closing this as conversation moved to #112.
